name: Deploy Frontend to Server

on:
  push:
    branches:
      - main # its main for now, but we can change it to reusable-table later

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code from main branch to github server
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean Install dependencies
        run: npm ci

      - name: Build project 
        run: npm run build

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/." 
          target: "/var/www" 
